[package]
name = "imi"
version = "0.3.4"
edition = "2021"

[[bin]]
name = "imi"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
rusqlite = { version = "0.32", features = ["bundled"] }
serde_json = "1"
